spring.application.name=SpringSeecurityApp

# Postgres support
spring.datasource.driver-class-name=${JDBC_DRIVER}
spring.datasource.url=jdbc:postgresql://${JDBC_HOST}:${JDBC_PORT}/${JDBC_DATABASE}?currentSchema=${JDBC_SCHEMA}
spring.datasource.username=${JDBC_USERNAME}
spring.datasource.password=${JDBC_PASSWORD}
spring.jpa.show-sql=true

# Config de JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Config del cache
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

jwt_secret=${JWT_SECRET}
jwt_expiration_minutes=${JWT_EXPIRATION_MINUTES}

app_name=${APP_NAME}