spring.application.name=SpringSeecurityApp

## traer los datos del database.properties
#spring.config.import=classpath:database.properties

# Postgres support
#spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driver-class-name=${JDBC_DRIVER}
spring.datasource.url=jdbc:postgresql://${JDBC_HOST}:${JDBC_PORT}/${JDBC_DATABASE}?currentSchema=${JDBC_SCHEMA}
spring.datasource.username=${JDBC_USERNAME}
spring.datasource.password=${JDBC_PASSWORD}
spring.jpa.show-sql=true

# Config de JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Security Config
#spring.security.user.name=agustin
#spring.security.user.password=1234

#Config del cache
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

#JDBC_USERNAME=postgres
#JDBC_PASSWORD=admin
#JWT_SECRET=my-secret-key
#
#jwt_secret=${JWT_SECRET}
#jwt_expiration_minutes=15
#
#app_name=Spring Security App

jwt_secret=${JWT_SECRET}
jwt_expiration_minutes=${JWT_EXPIRATION_MINUTES}

app_name=${APP_NAME}